/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset email */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm password reset with token */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change own password */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all employees */
        get: operations["listEmployees"];
        put?: never;
        /** Create new employee */
        post: operations["createEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get employee by ID */
        get: operations["getEmployee"];
        /** Update employee */
        put: operations["updateEmployee"];
        post?: never;
        /** Deactivate employee */
        delete: operations["deleteEmployee"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin reset employee password */
        post: operations["adminResetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all groups */
        get: operations["listGroups"];
        put?: never;
        /** Create new group */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get group by ID */
        get: operations["getGroup"];
        /** Update group */
        put: operations["updateGroup"];
        post?: never;
        /** Delete group */
        delete: operations["deleteGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get group assignments */
        get: operations["getGroupAssignments"];
        /** Update group assignments */
        put: operations["updateGroupAssignments"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get schedule entries */
        get: operations["getSchedule"];
        put?: never;
        /** Create schedule entry */
        post: operations["createScheduleEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/week": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get week view with all groups */
        get: operations["getWeekSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update schedule entry */
        put: operations["updateScheduleEntry"];
        post?: never;
        /** Delete schedule entry */
        delete: operations["deleteScheduleEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create multiple schedule entries */
        post: operations["bulkCreateScheduleEntries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-tracking/clock-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clock in (start work) */
        post: operations["clockIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-tracking/clock-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clock out (end work) */
        post: operations["clockOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-tracking/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current time entry (if clocked in) */
        get: operations["getCurrentTimeEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-tracking/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get time entries */
        get: operations["getTimeEntries"];
        put?: never;
        /** Create time entry (admin only) */
        post: operations["createTimeEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-tracking/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update time entry (admin only) */
        put: operations["updateTimeEntry"];
        post?: never;
        /** Delete time entry (admin only) */
        delete: operations["deleteTimeEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-tracking/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare time entries with schedule */
        get: operations["getTimeScheduleComparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/special-days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get special days */
        get: operations["getSpecialDays"];
        put?: never;
        /** Create special day */
        post: operations["createSpecialDay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/special-days/holidays/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brandenburg holidays for year */
        get: operations["getHolidays"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/special-days/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update special day */
        put: operations["updateSpecialDay"];
        post?: never;
        /** Delete special day */
        delete: operations["deleteSpecialDay"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get overview statistics (admin) */
        get: operations["getOverviewStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/employee/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get employee statistics */
        get: operations["getEmployeeStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get weekly statistics */
        get: operations["getWeeklyStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/timesheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export timesheet */
        get: operations["exportTimesheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export schedule */
        get: operations["exportSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResponse: {
            accessToken?: string;
            refreshToken?: string;
            expiresIn?: number;
            user?: components["schemas"]["Employee"];
        };
        RefreshTokenRequest: {
            refreshToken: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        PasswordResetConfirm: {
            token: string;
            newPassword: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        MessageResponse: {
            message?: string;
        };
        ErrorResponse: {
            error?: string;
            message?: string;
            details?: Record<string, never>;
        };
        Employee: {
            /** Format: int64 */
            id?: number;
            /** Format: email */
            email?: string;
            firstName?: string;
            lastName?: string;
            role?: components["schemas"]["EmployeeRole"];
            /**
             * Format: float
             * @description Contracted weekly hours (20-38)
             */
            weeklyHours?: number;
            /** @description Annual vacation days */
            vacationDaysPerYear?: number;
            /**
             * Format: float
             * @description Remaining vacation days this year
             */
            remainingVacationDays?: number;
            /**
             * Format: float
             * @description Current overtime balance in hours
             */
            overtimeBalance?: number;
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @enum {string} */
        EmployeeRole: "ADMIN" | "EMPLOYEE";
        CreateEmployeeRequest: {
            /** Format: email */
            email: string;
            firstName: string;
            lastName: string;
            /** @default EMPLOYEE */
            role: components["schemas"]["EmployeeRole"];
            /** Format: float */
            weeklyHours: number;
            /** @default 30 */
            vacationDaysPerYear: number;
        };
        UpdateEmployeeRequest: {
            /** Format: email */
            email?: string;
            firstName?: string;
            lastName?: string;
            role?: components["schemas"]["EmployeeRole"];
            /** Format: float */
            weeklyHours?: number;
            vacationDaysPerYear?: number;
            /** Format: float */
            remainingVacationDays?: number;
            /** Format: float */
            overtimeBalance?: number;
            active?: boolean;
        };
        Group: {
            /** Format: int64 */
            id?: number;
            name?: string;
            description?: string;
            /** @description Hex color for UI display */
            color?: string;
        };
        GroupWithMembers: components["schemas"]["Group"] & {
            members?: components["schemas"]["GroupAssignment"][];
        };
        CreateGroupRequest: {
            name: string;
            description?: string;
            color?: string;
        };
        GroupAssignment: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            employeeId?: number;
            employee?: components["schemas"]["Employee"];
            /** Format: int64 */
            groupId?: number;
            assignmentType?: components["schemas"]["AssignmentType"];
        };
        /** @enum {string} */
        AssignmentType: "PERMANENT" | "SPRINGER";
        GroupAssignmentRequest: {
            /** Format: int64 */
            employeeId: number;
            assignmentType: components["schemas"]["AssignmentType"];
        };
        ScheduleEntry: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            employeeId?: number;
            employee?: components["schemas"]["Employee"];
            /** Format: date */
            date?: string;
            /**
             * Format: time
             * @description HH:mm format
             */
            startTime?: string;
            /** Format: time */
            endTime?: string;
            /** @default 0 */
            breakMinutes: number;
            /** Format: int64 */
            groupId?: number;
            group?: components["schemas"]["Group"];
            entryType?: components["schemas"]["ScheduleEntryType"];
            notes?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @enum {string} */
        ScheduleEntryType: "WORK" | "VACATION" | "SICK" | "SPECIAL_LEAVE" | "TRAINING" | "EVENT";
        CreateScheduleEntryRequest: {
            /** Format: int64 */
            employeeId: number;
            /** Format: date */
            date: string;
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
            /** @default 0 */
            breakMinutes: number;
            /** Format: int64 */
            groupId?: number;
            entryType: components["schemas"]["ScheduleEntryType"];
            notes?: string;
        };
        UpdateScheduleEntryRequest: {
            /** Format: date */
            date?: string;
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
            breakMinutes?: number;
            /** Format: int64 */
            groupId?: number;
            entryType?: components["schemas"]["ScheduleEntryType"];
            notes?: string;
        };
        WeekSchedule: {
            /** Format: date */
            weekStart?: string;
            /** Format: date */
            weekEnd?: string;
            days?: components["schemas"]["DaySchedule"][];
            specialDays?: components["schemas"]["SpecialDay"][];
        };
        DaySchedule: {
            /** Format: date */
            date?: string;
            /** @enum {string} */
            dayOfWeek?: "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY";
            isHoliday?: boolean;
            holidayName?: string;
            entries?: components["schemas"]["ScheduleEntry"][];
            byGroup?: {
                [key: string]: components["schemas"]["ScheduleEntry"][];
            };
        };
        TimeEntry: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            employeeId?: number;
            employee?: components["schemas"]["Employee"];
            /** Format: date */
            date?: string;
            /** Format: date-time */
            clockIn?: string;
            /** Format: date-time */
            clockOut?: string;
            breakMinutes?: number;
            entryType?: components["schemas"]["TimeEntryType"];
            /** @description Calculated worked time in minutes */
            workedMinutes?: number;
            notes?: string;
            /** Format: int64 */
            editedBy?: number;
            /** Format: date-time */
            editedAt?: string;
            editReason?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @enum {string} */
        TimeEntryType: "WORK" | "VACATION" | "SICK" | "SPECIAL_LEAVE" | "TRAINING" | "EVENT";
        ClockInRequest: {
            notes?: string;
        };
        ClockOutRequest: {
            /** @default 0 */
            breakMinutes: number;
            notes?: string;
        };
        CreateTimeEntryRequest: {
            /** Format: int64 */
            employeeId: number;
            /** Format: date */
            date: string;
            /** Format: date-time */
            clockIn: string;
            /** Format: date-time */
            clockOut: string;
            /** @default 0 */
            breakMinutes: number;
            /** @default WORK */
            entryType: components["schemas"]["TimeEntryType"];
            notes?: string;
            editReason?: string;
        };
        UpdateTimeEntryRequest: {
            /** Format: date-time */
            clockIn?: string;
            /** Format: date-time */
            clockOut?: string;
            breakMinutes?: number;
            entryType?: components["schemas"]["TimeEntryType"];
            notes?: string;
            /** @description Required when admin edits entry */
            editReason?: string;
        };
        TimeScheduleComparison: {
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            entries?: components["schemas"]["DayComparison"][];
            summary?: components["schemas"]["ComparisonSummary"];
        };
        DayComparison: {
            /** Format: date */
            date?: string;
            scheduled?: components["schemas"]["ScheduleEntry"];
            actual?: components["schemas"]["TimeEntry"];
            scheduledMinutes?: number;
            actualMinutes?: number;
            differenceMinutes?: number;
            /** @enum {string} */
            status?: "MATCH" | "EARLY" | "LATE" | "OVERTIME" | "UNDERTIME" | "MISSING" | "UNSCHEDULED";
        };
        ComparisonSummary: {
            totalScheduledMinutes?: number;
            totalActualMinutes?: number;
            totalDifferenceMinutes?: number;
            daysWorked?: number;
            daysScheduled?: number;
        };
        SpecialDay: {
            /** Format: int64 */
            id?: number;
            /** Format: date */
            date?: string;
            name?: string;
            dayType?: components["schemas"]["SpecialDayType"];
            /** @description If true, affects all employees */
            affectsAll?: boolean;
            notes?: string;
        };
        /** @enum {string} */
        SpecialDayType: "HOLIDAY" | "CLOSURE" | "TEAM_DAY" | "EVENT";
        CreateSpecialDayRequest: {
            /** Format: date */
            date: string;
            name: string;
            dayType: components["schemas"]["SpecialDayType"];
            /** @default true */
            affectsAll: boolean;
            notes?: string;
        };
        OverviewStatistics: {
            /** Format: date */
            month?: string;
            totalEmployees?: number;
            employeeStats?: components["schemas"]["EmployeeStatisticsSummary"][];
            /** Format: float */
            totalScheduledHours?: number;
            /** Format: float */
            totalWorkedHours?: number;
            /** Format: float */
            totalOvertimeHours?: number;
            sickDays?: number;
            vacationDays?: number;
        };
        EmployeeStatisticsSummary: {
            employee?: components["schemas"]["Employee"];
            /** Format: float */
            scheduledHours?: number;
            /** Format: float */
            workedHours?: number;
            /** Format: float */
            overtimeHours?: number;
            /** Format: float */
            remainingVacationDays?: number;
        };
        EmployeeStatistics: {
            employee?: components["schemas"]["Employee"];
            /** Format: date */
            month?: string;
            /**
             * Format: float
             * @description Expected hours based on contract
             */
            contractedHours?: number;
            /** Format: float */
            scheduledHours?: number;
            /** Format: float */
            workedHours?: number;
            /** Format: float */
            overtimeHours?: number;
            /**
             * Format: float
             * @description Cumulative overtime balance
             */
            overtimeBalance?: number;
            vacationDaysUsed?: number;
            /** Format: float */
            vacationDaysRemaining?: number;
            sickDays?: number;
            dailyBreakdown?: components["schemas"]["DayStatistics"][];
        };
        DayStatistics: {
            /** Format: date */
            date?: string;
            /** Format: float */
            scheduledHours?: number;
            /** Format: float */
            workedHours?: number;
            entryType?: components["schemas"]["ScheduleEntryType"];
        };
        WeeklyStatistics: {
            /** Format: date */
            weekStart?: string;
            /** Format: date */
            weekEnd?: string;
            byEmployee?: components["schemas"]["EmployeeWeekSummary"][];
            byGroup?: components["schemas"]["GroupWeekSummary"][];
            /** Format: float */
            totalScheduledHours?: number;
            /** Format: float */
            totalWorkedHours?: number;
        };
        EmployeeWeekSummary: {
            employee?: components["schemas"]["Employee"];
            /** Format: float */
            scheduledHours?: number;
            /** Format: float */
            workedHours?: number;
            daysWorked?: number;
        };
        GroupWeekSummary: {
            group?: components["schemas"]["Group"];
            /** Format: float */
            totalScheduledHours?: number;
            staffedDays?: number;
            understaffedDays?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful login */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Token refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Reset email sent (if email exists) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Password reset successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Invalid or expired token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Invalid current password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    listEmployees: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of employees */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"][];
                };
            };
        };
    };
    createEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeRequest"];
            };
        };
        responses: {
            /** @description Employee created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employee found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            /** @description Employee not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmployeeRequest"];
            };
        };
        responses: {
            /** @description Employee updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            /** @description Employee not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employee deactivated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Employee not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminResetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Password reset email sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Group created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupWithMembers"];
                };
            };
            /** @description Group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Group updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
        };
    };
    deleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGroupAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group assignments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupAssignment"][];
                };
            };
        };
    };
    updateGroupAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupAssignmentRequest"][];
            };
        };
        responses: {
            /** @description Assignments updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupAssignment"][];
                };
            };
        };
    };
    getSchedule: {
        parameters: {
            query: {
                startDate: string;
                endDate: string;
                employeeId?: number;
                groupId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schedule entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntry"][];
                };
            };
        };
    };
    createScheduleEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduleEntryRequest"];
            };
        };
        responses: {
            /** @description Entry created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntry"];
                };
            };
        };
    };
    getWeekSchedule: {
        parameters: {
            query: {
                /** @description Monday of the week (ISO date) */
                weekStart: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Week schedule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekSchedule"];
                };
            };
        };
    };
    updateScheduleEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScheduleEntryRequest"];
            };
        };
        responses: {
            /** @description Entry updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntry"];
                };
            };
        };
    };
    deleteScheduleEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bulkCreateScheduleEntries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduleEntryRequest"][];
            };
        };
        responses: {
            /** @description Entries created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntry"][];
                };
            };
        };
    };
    clockIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ClockInRequest"];
            };
        };
        responses: {
            /** @description Clocked in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeEntry"];
                };
            };
            /** @description Already clocked in */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clockOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ClockOutRequest"];
            };
        };
        responses: {
            /** @description Clocked out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeEntry"];
                };
            };
            /** @description Not clocked in */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentTimeEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current entry or null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeEntry"];
                };
            };
            /** @description Not currently clocked in */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTimeEntries: {
        parameters: {
            query: {
                startDate: string;
                endDate: string;
                /** @description Admin only - filter by employee */
                employeeId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Time entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeEntry"][];
                };
            };
        };
    };
    createTimeEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTimeEntryRequest"];
            };
        };
        responses: {
            /** @description Entry created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeEntry"];
                };
            };
        };
    };
    updateTimeEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTimeEntryRequest"];
            };
        };
        responses: {
            /** @description Entry updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeEntry"];
                };
            };
        };
    };
    deleteTimeEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getTimeScheduleComparison: {
        parameters: {
            query: {
                startDate: string;
                endDate: string;
                employeeId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comparison data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeScheduleComparison"];
                };
            };
        };
    };
    getSpecialDays: {
        parameters: {
            query: {
                year: number;
                includeHolidays?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Special days */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialDay"][];
                };
            };
        };
    };
    createSpecialDay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpecialDayRequest"];
            };
        };
        responses: {
            /** @description Special day created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialDay"];
                };
            };
        };
    };
    getHolidays: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Holidays */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialDay"][];
                };
            };
        };
    };
    updateSpecialDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpecialDayRequest"];
            };
        };
        responses: {
            /** @description Special day updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialDay"];
                };
            };
        };
    };
    deleteSpecialDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Special day deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOverviewStatistics: {
        parameters: {
            query: {
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overview statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewStatistics"];
                };
            };
        };
    };
    getEmployeeStatistics: {
        parameters: {
            query: {
                month: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employee statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeStatistics"];
                };
            };
        };
    };
    getWeeklyStatistics: {
        parameters: {
            query: {
                weekStart: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Weekly statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyStatistics"];
                };
            };
        };
    };
    exportTimesheet: {
        parameters: {
            query: {
                employeeId?: number;
                month: string;
                format: "pdf" | "xlsx";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timesheet file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    exportSchedule: {
        parameters: {
            query: {
                weekStart: string;
                format: "pdf" | "xlsx";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schedule file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
}
